version: '3'
services:
  api:
    build: ./api
    ports:
      - "4270:8080"
    volumes:
      - explorer-db:/go/src/github.com/EnsicoinDevs/ensicoin-explorer/api/db
    environment:
      - GIN_MODE=release
      - API_NODE=172.17.0.1:4225
  frontend:
    build: ./frontend
    ports:
      - "4271:8080"

volumes:
  explorer-db:
