version: '3'
services:
  api:
    build: ./api
    ports:
      - "4270:8080"
    volumes:
      - explorer-db:/app/db
    environment:
      - GIN_MODE=release
      - API_NODE=172.0.0.1:4225
  frontend:
    build: ./frontend
    ports:
      - "4271:80"

volumes:
  explorer-db:
